export enum repositories {
  admin_repository = 'admin_repository',
  user_repository = 'user_repository',
  category_repository = 'category_repository',
  article_repository = 'article_repository',
  question_repository = 'question_repository',
  requested_question_repository = 'requested_question_repository',
  challenge_type_repository = 'challenge_type_repository',
  challenge_repository = 'challenge_repository',
  quiz_repository = 'quiz_repository',
  quiz_question_repository = 'quiz_question_repository',
  quiz_answer_repository = 'quiz_answer_repository',
  user_quiz_repository = 'user_quiz_repository',
  comment_repository = 'comment_repository',
  article_view_repository = 'article_view_repository',
  question_view_repository = 'question_view_repository',
  user_point_repository = 'user_point_repository',
  skill_repository = 'skill_repository',
  social_media_repository = 'social_media_repository',
}
